import os
import re

from dotenv import load_dotenv
import boto3
from botocore.config import Config

load_dotenv()

# R2 Configuration
ACCOUNT_ID = os.getenv("CLOUDFLARE_ACCOUNT_ID")
ACCESS_KEY = os.getenv("CLOUDFLARE_R2_ACCESS_KEY_ID")
SECRET_KEY = os.getenv("CLOUDFLARE_R2_SECRET_ACCESS_KEY")
BUCKET_NAME = os.getenv("CLOUDFLARE_R2_BUCKET_NAME")

_r2_client = None

def get_r2_client():
    """Lazy-initialized R2 client. Allows server to start without R2 creds."""
    global _r2_client
    if _r2_client is None:
        if not all([ACCOUNT_ID, ACCESS_KEY, SECRET_KEY, BUCKET_NAME]):
            raise RuntimeError("R2 credentials not configured. Set CLOUDFLARE_* env vars.")
        _r2_client = boto3.client(
            "s3",
            endpoint_url=f"https://{ACCOUNT_ID}.r2.cloudflarestorage.com",
            aws_access_key_id=ACCESS_KEY,
            aws_secret_access_key=SECRET_KEY,
            config=Config(signature_version="s3v4"),
            region_name="auto"
        )
    return _r2_client

# For backward compat with tests that monkeypatch r2_client
# Use a callable that can be replaced
class _R2ClientProxy:
    """Forwards the S3 calls joyverse makes to the lazily-built real client.

    Each method resolves the client at call time rather than holding one, so
    the R2-free startup behaviour (and the test fixtures) still work.
    """

    def get_object(self, **kwargs):
        return get_r2_client().get_object(**kwargs)

    def put_object(self, **kwargs):
        return get_r2_client().put_object(**kwargs)

    def list_objects_v2(self, **kwargs):
        # Needed by list_topics and by get_data's miss path, both of which
        # enumerate a user's topics. Omitting this made topic discovery fail
        # against real R2 while passing every test, because FakeR2 always had
        # the method.
        return get_r2_client().list_objects_v2(**kwargs)

    def head_object(self, **kwargs):
        # Metadata only, so get_file can report size and type without
        # downloading the object.
        return get_r2_client().head_object(**kwargs)

    def generate_presigned_url(self, *args, **kwargs):
        # Share links. The object stays private; only the signature grants
        # time-limited access.
        return get_r2_client().generate_presigned_url(*args, **kwargs)

    def delete_object(self, **kwargs):
        return get_r2_client().delete_object(**kwargs)

    def delete_objects(self, **kwargs):
        return get_r2_client().delete_objects(**kwargs)

r2_client = _R2ClientProxy()

# ==========================================
# DYNAMIC KEY BUILDERS (Multi-user)
# ==========================================

def _safe_segment(value: str) -> str:
    """Rejects path-traversal attempts in a user-supplied key segment.

    Defence in depth. The primary guarantee is that user_id is server-minted
    and so can never contain a separator, but a user_id arriving from a token
    or a future caller must still be unable to escape its own prefix.
    """
    if "/" in value or "\\" in value or ".." in value or value.strip() == "":
        raise ValueError(f"Invalid key segment: {value!r}")
    return value


def _safe_user_id(value: str) -> str:
    """Validate a user_id before it becomes part of an R2 key.

    user_id is generated by identity.new_user_id(), so anything that does not
    match that exact shape did not come from us -- the registry namespace in
    particular must never be writable as if it were a user.
    """
    from joyverse.identity import is_user_id

    if not is_user_id(value):
        raise ValueError(f"Invalid user id: {value!r}")
    return value


def get_profile_key(user_id: str) -> str:
    return f"users/{_safe_user_id(user_id)}/profile.md"

def get_bio_key(user_id: str) -> str:
    return f"users/{_safe_user_id(user_id)}/bio.md"

def get_memory_key(user_id: str) -> str:
    return f"users/{_safe_user_id(user_id)}/memory.json"

def get_data_key(user_id: str, topic: str) -> str:
    # Use topic-specific filename based on known schemas
    filename_map = {
        "dsa": "progress.json",
        "projects": "active.json",
        "skills": "stack.json",
        "reading": "list.json",
        "games": "played.json",
    }
    filename = filename_map.get(topic, "progress.json")
    return f"users/{_safe_user_id(user_id)}/data/{_safe_segment(topic)}/{filename}"


# ==========================================
# OAUTH CONFIGURATION
# ==========================================
# Loaded from the environment so no provider name or tenant is hardcoded in
# the application. The server stays usable with bearer auth alone when
# OAUTH_ENABLED is false, which is why nothing here raises at import time.

OAUTH_ENABLED = os.getenv("OAUTH_ENABLED", "false").strip().lower() in (
    "1", "true", "yes", "on"
)
AUTH0_DOMAIN = os.getenv("AUTH0_DOMAIN", "").strip()
AUTH0_AUDIENCE = os.getenv("AUTH0_AUDIENCE", "").strip()
AUTH0_CLIENT_ID = os.getenv("AUTH0_CLIENT_ID", "").strip()
PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "").strip().rstrip("/")

# Scopes this resource server understands. Advertised in the discovery
# document and enforced per tool in run.py.
READ_SCOPE = "joyverse:read"
WRITE_SCOPE = "joyverse:write"
SUPPORTED_SCOPES = [READ_SCOPE, WRITE_SCOPE]


def issuer_url() -> str:
    """The OAuth issuer, normalised with a trailing slash.

    Auth0's issuer is "https://tenant/" WITH the slash and PyJWT compares the
    claim as an exact string, so a missing slash would fail every token with a
    confusing "wrong issuer". Normalising here keeps that mistake out of the
    caller's hands.
    """
    if not AUTH0_DOMAIN:
        raise RuntimeError(
            "AUTH0_DOMAIN is not set. Add it to .env to enable OAuth.")
    domain = AUTH0_DOMAIN.rstrip("/")
    if not domain.startswith(("http://", "https://")):
        domain = f"https://{domain}"
    return f"{domain}/"


def authorization_servers() -> list:
    """Issuers listed in the RFC 9728 discovery document.

    The value MUST be byte-identical to the `issuer` field in the
    authorization server's own metadata, trailing slash included. A compliant
    MCP client fetches {AS}/.well-known/oauth-authorization-server and compares
    the two as strings; Auth0's issuer ends in "/", so stripping it here makes
    the client refuse to connect with:

        Authorization server metadata issuer mismatch:
        https://tenant.auth0.com/ != https://tenant.auth0.com

    That is why this returns issuer_url() unmodified while token validation
    uses the same string for PyJWT's exact `iss` match.
    """
    return [issuer_url()] if OAUTH_ENABLED and AUTH0_DOMAIN else []


def resource_url() -> str:
    """The canonical URL clients treat as this MCP resource."""
    if not PUBLIC_BASE_URL:
        raise RuntimeError(
            "PUBLIC_BASE_URL is not set. Add it to .env to advertise "
            "OAuth discovery metadata.")
    return f"{PUBLIC_BASE_URL}/mcp"

# ==========================================
# FILE STORAGE LIMITS
# ==========================================
# Pooled across every client: there is no per-client cap, so one client
# producing gigabytes does not starve the others.
STORAGE_ROOT = "storage"


def _env_int(name: str, default: int) -> int:
    """Read a byte-count limit from the environment."""
    raw = os.getenv(name, "").strip()
    if not raw:
        return default
    try:
        value = int(raw)
    except ValueError:
        return default
    return value if value > 0 else default


MB = 1024 * 1024
GB = 1024 * MB

# Per-file ceiling. Nothing can currently reach this: the only upload paths are
# save_file_from_url and save_file_base64, which is capped by MAX_INLINE_BYTES.
# It is left generous because the binding constraint is the per-user quota
# below, not any single object.
MAX_FILE_BYTES = _env_int("JOYVERSE_MAX_FILE_MB", 2048) * MB
MAX_USER_BYTES = _env_int("JOYVERSE_MAX_USER_GB", 50) * GB

# Largest file save_file_base64 will accept in one call. Base64 inflates by a
# third and the payload is charged to the agent's context window, so this stays
# small on purpose. Larger files need a transport that does not route bytes
# through the model, which does not exist yet.
MAX_INLINE_BYTES = _env_int("JOYVERSE_MAX_INLINE_MB", 8) * MB

# Guards for server-side URL fetches.
FETCH_TIMEOUT_SECONDS = _env_int("JOYVERSE_FETCH_TIMEOUT", 30)
MAX_REDIRECTS = 5

# Conversation logs are stored one object per day, named by date. Validated
# here because the date is user-supplied and becomes a key segment.
DATE_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}$")


def get_log_key(user_id: str, date: str) -> str:
    """R2 key for one day's conversation log.

    One object per day, rather than a single growing log, so that asking about
    a date reads one small object instead of scanning all history. The date is
    validated strictly before it becomes a path segment -- an unvalidated date
    is user input and this is a key.
    """
    if not DATE_PATTERN.match(date or ""):
        raise ValueError(f"Invalid date: {date!r}. Use YYYY-MM-DD.")
    return f"users/{_safe_user_id(user_id)}/logs/{date}.jsonl"
